name: Build Jekyll site
on:
 push:
   branches: ["development"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  tests:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    steps:
      - name: Checking healt of site
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://kdimakon.github.io/static2/
          max-attempts: 3
          retry-delay: 5s
      - name: The job has failed
        if: ${{ failure() }}
        run: echo fails
  pull_request_to_main:
    runs-on: ubuntu-latest
    needs: [build, deploy, tests]
    if: contains(needs.tests.result, 'success' ) 
    steps:
      - uses: actions/checkout@master
      - name: Merge development into production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: production
          github_token: ${{ secrets.MERGE_TOKEN }}

        